### ISSUE TITLE
增加 nodelay 配置

### ISSUE THREAD

**Issue by hangj** [CandyMi/skynet-lua-websocket#2]
希望 `local wss = wsserver:new { fd = id, cls = ws }` 可以加个 nodelay 配置

**Comment by hangj** [comment]
还希望 headers 传给 ws:on_open 
因为好多小程序的 session_key 都是放在 header 里的，方便做验证

**Comment by CandyMi** [comment]
@hangj 

  谢谢你的建议. `nodelay`参数支持已经添加, 你可以尝试从`master`分支中拿到代码.

**Comment by CandyMi** [comment]
@hangj  

  关于传递`headers`的建议我也已经实现了.

  但是我将`headers`交由`ws:ctor`中的opt参数包裹, 你可以这样引用:`opt.headers`

**Comment by hangj** [comment]
@CandyMi thanks!
